#!/bin/bash

#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# devstack/plugin.sh
# networking-dpm actions for devstack plugin framework

# Save trace setting
XTRACE=$(set +o | grep xtrace)
set +o xtrace


function is_neutron_ovs_base_plugin {
    # macvtap doesn't use OVS
    return 1
}

function neutron_plugin_create_nova_conf {
    :
}

function neutron_plugin_install_agent_packages {
    # Required as zhmcclient does not yet show up in requirements.txt
    # but is hard coded in tox dependencies
    sudo pip install zhmcclient
    setup_develop $DEST/networking-dpm
}

function neutron_plugin_configure_debug_command {
    :
}

function neutron_plugin_configure_dhcp_agent {
    :
}

function neutron_plugin_configure_l3_agent {
    :
}

function neutron_plugin_configure_plugin_agent {
    # Only the NooPFirewallDriver is supported. If not set, the agent will
    # terminate.
    iniset /$Q_PLUGIN_CONF_FILE securitygroup firewall_driver noop
    AGENT_BINARY="$NEUTRON_BIN_DIR/neutron-dpm-agent"
}

function neutron_plugin_setup_interface_driver {
    :
}

function neutron_plugin_check_adv_test_requirements {
    :
}

# Restore xtrace
$XTRACE
